#!/bin/bash

export WOOCOMMERCE_CURRENT_TESTED_VERSION=${WOOCOMMERCE_TESTED_VERSION}
export WOOCOMMERCE_RELEASE_FILE=${WOOCOMMERCE_RELEASES_FILE}

echo "Version from env and a file from which it will be taken: " . ${WOOCOMMERCE_CURRENT_TESTED_VERSION} . "\n" . ${WOOCOMMERCE_RELEASE_FILE} . "\n"

if [[ ${WOOCOMMERCE_CURRENT_TESTED_VERSION} = "latest" ]]; then
   WOOCOMMERCE_VERSION=$(awk 'NR==1 {print; exit}' ${WOOCOMMERCE_RELEASE_FILE})
elif [[ ${WOOCOMMERCE_CURRENT_TESTED_VERSION} = "2" ]]; then
   WOOCOMMERCE_VERSION=$(awk 'NR==2 {print; exit}' ${WOOCOMMERCE_RELEASE_FILE})
elif [[  ${WOOCOMMERCE_CURRENT_TESTED_VERSION} = "3" ]]; then
   WOOCOMMERCE_VERSION=$(awk 'NR==3 {print; exit}' ${WOOCOMMERCE_RELEASE_FILE})
fi

echo "Real current version: " . ${WOOCOMMERCE_VERSION}

