#!/bin/bash

export WOOCOMMERCE_CURRENT_TESTED_VERSION=${WOOCOMMERCE_TESTED_VERSION}
export WOOCOMMERCE_RELEASE_FILE=${WOOCOMMERCE_RELEASES_FILE}

if [[ ${WOOCOMMERCE_CURRENT_TESTED_VERSION} = "latest" ]]; then
   export WOOCOMMERCE_VERSION=$(awk 'NR==1 {print; exit}' ${WOOCOMMERCE_RELEASE_FILE})
elif [[ ${WOOCOMMERCE_CURRENT_TESTED_VERSION} = "2" ]]; then
   export WOOCOMMERCE_VERSION=$(awk 'NR==2 {print; exit}' ${WOOCOMMERCE_RELEASE_FILE})
elif [[  ${WOOCOMMERCE_CURRENT_TESTED_VERSION} = "3" ]]; then
   export WOOCOMMERCE_VERSION=$(awk 'NR==3 {print; exit}' ${WOOCOMMERCE_RELEASE_FILE})
fi

